from pathlib import Path
from subprocess import run

regions = {
    'gangwon': ('강원', {'춘천시':'chuncheon','원주시':'wonju','강릉시':'gangneung','동해시':'donghae','태백시':'taebaek','속초시':'sokcho','삼척시':'samcheok','홍천군':'hongcheon','횡성군':'hoengseong','영월군':'yeongwol','평창군':'pyeongchang','정선군':'jeongseon','철원군':'cheorwon','화천군':'hwacheon','양구군':'yanggu','인제군':'inje','고성군':'goseong','양양군':'yangyang'}),
    'gyeongbuk': ('경북', {'포항시':'pohang','경주시':'gyeongju','김천시':'gimcheon','안동시':'andong','구미시':'gumi','영주시':'yeongju','영천시':'yeongcheon','상주시':'sangju','문경시':'mungyeong','경산시':'gyeongsan','의성군':'uiseong','청송군':'cheongsong','영양군':'yeongyang','영덕군':'yeongdeok','청도군':'cheongdo','고령군':'goryeong','성주군':'seongju','칠곡군':'chilgok','예천군':'yecheon','봉화군':'bonghwa','울진군':'uljin','울릉군':'ulleung','군위군':'gunwi'}),
    'jeju': ('제주', {'제주시':'jeju-si','서귀포시':'seogwipo'})
}
landing = '''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{region} 스마트무인자판기 설치 및 시·군별 무료 견적 안내"><title>{region} 스마트무인자판기 설치 안내 | 수행코치</title><link rel="stylesheet" href="../installation.css"></head><body><header class="site-header"><a class="brand" href="../index.html"><span class="brand-mark">S</span><span>수행코치 <small>VENDING STUDIO</small></span></a></header><main><section class="hero"><div class="hero-copy"><p class="eyebrow">{region} INSTALLATION GUIDE</p><h1>{region} 공간에 맞는<br><em>무인자판기</em><br>설치 안내</h1><p>{region} 지역의 산업·관광·오피스·주거공간에 맞춰 상품 구성과 운영 동선을 설계합니다.</p></div><div class="hero-image"><img src="../1234.png" alt="{region} 스마트무인자판기"></div></section><section class="section"><div class="section-head"><div><p class="eyebrow">LOCAL CITY GUIDE</p><h2>설치할 지역을<br><em>선택해주세요.</em></h2></div><p>지역을 선택하면 해당 지역의 설치 안내와 무료 견적 상담으로 연결됩니다.</p></div><div class="region-grid">{cards}</div></section><section class="cta"><h2>{region} 설치 상담을<br><em>시작해보세요.</em></h2><a class="button" href="../index.html#consult">무료 상담받기 <span>→</span></a></section></main></body></html>'''
page = '''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{area} 스마트무인자판기 설치 비용·무료 견적 안내"><title>{area} 스마트무인자판기 설치 비용·무료 견적 | 수행코치</title><link rel="stylesheet" href="../../../installation.css"></head><body><main><section class="hero"><div class="hero-copy"><p class="eyebrow">{region} {area} INSTALLATION GUIDE</p><h1>{region} {area}<br><em>무인자판기</em><br>설치 안내</h1><p>{region} {area} 지역의 산업·관광·오피스·주거공간에 맞춰 상품 구성과 운영 동선을 설계합니다.</p></div><div class="hero-image"><img src="../../../1234.png" alt="{area} 스마트무인자판기"><div class="hero-label"><strong>{area} 지역 상담</strong><span>무료 견적 안내</span></div></div></section><section class="section process"><h2>{area} 설치 상담<br><em>5단계 안내</em></h2><div class="steps"><article><b>01</b><strong>입지 상담</strong><p>공간과 고객 흐름 확인</p></article><article><b>02</b><strong>맞춤 견적</strong><p>기기·상품·결제 안내</p></article><article><b>03</b><strong>설치 세팅</strong><p>결제 연결과 상품 진열</p></article><article><b>04</b><strong>운영 안내</strong><p>재고·매출 관리</p></article></div></section><section class="cta"><h2>{area} 무료 설치 상담</h2><a class="button" href="../../../index.html#consult">상담 신청하기</a></section></main><footer class="site-footer"><a href="../../{group}.html">← {region} 지역 선택</a></footer></body></html>'''
for group, (region, areas) in regions.items():
    cards = ''.join(f'<a class="region-card" href="{group}/{slug}/"><span><b>{area}</b><small>{area} 설치 안내</small></span><span>↗</span></a>' for area, slug in areas.items())
    Path('regions', f'{group}.html').write_text(landing.format(region=region, cards=cards), encoding='utf-8')
    for area, slug in areas.items():
        folder = Path('regions', group, slug)
        folder.mkdir(parents=True, exist_ok=True)
        (folder / 'index.html').write_text(page.format(region=region, area=area, group=group), encoding='utf-8')
print('Generated Gangwon, Gyeongbuk, and Jeju regional directories.')
run(["python", "add_regional_keywords.py"], check=True)
